### ISSUE TITLE
Provide documentation prerequisites for AwsEksResourceDetector

### ISSUE THREAD

**Issue by lorchda** [open-telemetry/opentelemetry-python-contrib#1384]
Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry/). If so, please [open an issue on opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

**Is your feature request related to a problem?**

Problem: Have to read the source code for `AwsEksResourceDetector` to understand which permissions and resources are needed in the cluster for it to work.

**Describe the solution you'd like**

Solution: Provide documentation on prerequisites.

First prerequisite: permissions for service account role

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-awseksresourcedetector-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - aws-auth
      - cluster-info
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-awseksresourcedetector-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-awseksresourcedetector-role
subjects:
  - kind: ServiceAccount
    name: {{your_service_account}}
    namespace: {{namespace_of_your_service_account}}
  - kind: ServiceAccount
    name: {{your_service_account}}
    namespace: {{namespace_of_your_service_account}}
```

Furthermore, a configmap `cluster-info` in `amazon-cloudwatch` is required with the following information:

```yaml
# create configmap for cluster name and aws region for CloudWatch Logs
# need to replace the placeholders {{cluster_name}} and {{region_name}}
apiVersion: v1
data:
  cluster.name: {{cluster_name}}
  logs.region: {{region_name}}
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: amazon-cloudwatch
```
