### ISSUE TITLE
boto3sqs doesn't work using boto3.Session().client()

### ISSUE THREAD

**Issue by rdkr** [open-telemetry/opentelemetry-python-contrib#1996]
**Describe your environment**
Python 3.8 in Docker on Linux

**Steps to reproduce**
I used this script to reproduce the issue in isolation:

```
QUEUE = "..."

import time
import sys
import boto3

sqs = boto3.Session().client("sqs")


def do_a_thing(message):
    print(message["Body"], message.get("MessageAttributes"))
    time.sleep(1)
    sqs.delete_message(
        QueueUrl=QUEUE,
        ReceiptHandle=message["ReceiptHandle"],
    )


if sys.argv[1] == "tx":
    while True:
        response = sqs.send_message(QueueUrl=QUEUE, MessageBody="ok")
        print(response)
        time.sleep(5)

elif sys.argv[1] == "rx":
    while True:
        messages = sqs.receive_message(
            QueueUrl=QUEUE,
            MessageAttributeNames=["All"],
            MaxNumberOfMessages=10,
            WaitTimeSeconds=10,
        ).get("Messages", [])

        for message in messages:
            try:
                do_a_thing(message)
            except:
                print("failed to do a thing")
```
```
FROM python:3.8

RUN pip install boto3 opentelemetry-distro opentelemetry-exporter-otlp
RUN opentelemetry-bootstrap -a install

COPY sqs.py sqs.py
```
```
version: "2"
services:

  tx:
    build:
      context: .
    environment:
      - OTEL_SERVICE_NAME=test
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION=eu-west-2
    command: opentelemetry-instrument python -u sqs.py tx

  rx:
    build:
      context: .
    environment:
      - OTEL_SERVICE_NAME=test
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION=eu-west-2
    command: opentelemetry-instrument python -u sqs.py rx
```

**What is the expected behavior?**
The same traces when creating a client with `boto3.Session().client("sqs")` as with `boto3.client("sqs")`.

**What is the actual behavior?**
`boto3sqs` doesn't appear to instrument clients created with `boto3.Session().client("sqs")`. There is no parent ID in the SQS message received when using `boto3.Session().client("sqs")`.
