### ISSUE TITLE
FastAPI `uninstrument` disallows adding more middlewares with `fastapi@>=0.91` and `starlette@>=0.24`

### ISSUE THREAD

**Issue by maxkomarychev** [open-telemetry/opentelemetry-python-contrib#2042]
Uninstrument is breaking subsequent calls to `add_middleware` due to recent changes in `starlette` https://github.com/encode/starlette/pull/2017 and latest version of `fastapi@>=0.91`.

[Call to `build_middleware_stack`](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/4f6618324d02e663ddcc24fe68d5241ca1620a48/instrumentation/opentelemetry-instrumentation-fastapi/src/opentelemetry/instrumentation/fastapi/__init__.py#L257) makes an instance of FastAPI and [starelette to think  that application is already running](https://github.com/encode/starlette/blob/2c066afa753d7ff1c021df7e0340dab524766c0c/starlette/applications.py#L129)

**Describe your environment**

Python 3.9.9

```toml
opentelemetry-distro = "^0.41b0"
opentelemetry-exporter-otlp = "^1.20.0"
opentelemetry-instrumentation-aws-lambda = "^0.41b0"
opentelemetry-instrumentation-dbapi = "^0.41b0"
opentelemetry-instrumentation-logging = "^0.41b0"
opentelemetry-instrumentation-sqlite3 = "^0.41b0"
opentelemetry-instrumentation-urllib = "^0.41b0"
opentelemetry-instrumentation-wsgi = "^0.41b0"
opentelemetry-instrumentation-asgi = "^0.41b0"
opentelemetry-instrumentation-fastapi = "^0.41b0"
opentelemetry-instrumentation-grpc = "^0.41b0"
opentelemetry-instrumentation-httpx = "^0.41b0"
opentelemetry-instrumentation-requests = "^0.41b0"
opentelemetry-instrumentation-sqlalchemy = "^0.41b0"
opentelemetry-instrumentation-urllib3 = "^0.41b0"
```

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

```python
from starlette.middleware.cors import CORSMiddleware
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor

app = FastAPI(...)

FastAPIInstrumentor.uninstrument_app(app)

app.add_middleware(
    CORSMiddleware,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
```

**What is the expected behavior?**
What did you expect to see?

`FastAPIInstrumentor.uninstrument_app` should not break ability to add more middlewares

**What is the actual behavior?**
What did you see instead?

Application crashes:

```
  File "/xxx/.venv/lib/python3.9/site-packages/starlette/applications.py", line 139, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
```

**Additional context**
