### ISSUE TITLE
OTEL Kubernetes Instrumentation env var OTEL_PYTHON_DISABLED_INSTRUMENTATIONS don't disable specified packages.

### ISSUE THREAD

**Issue by AlejandroReBa** [open-telemetry/opentelemetry-python-contrib#2458]
**Describe your environment**

_Platform environment_
Google Kubernetes Engine: 1.27.11-gke.1062000
[OpenTelemetry Operator v.0.98.0](https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.98.0)
[OpenTelemetry Contrib Collector - v0.98.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.98.0)
[OpenTelemetry Python Contributor - v0.44b0](https://github.com/open-telemetry/opentelemetry-python-contrib/releases/tag/v0.44b0)
[OpenTelemetry Instrumentation GRPC - v0.44b0](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-grpc)

List of OpenTelemetry packages installed:

```
opentelemetry-api==1.23.0
opentelemetry-distro==0.44b0
opentelemetry-exporter-otlp-proto-common==1.23.0
opentelemetry-exporter-otlp-proto-http==1.23.0
opentelemetry-instrumentation==0.44b0
opentelemetry-instrumentation-aio-pika==0.44b0
opentelemetry-instrumentation-aiohttp-client==0.44b0
opentelemetry-instrumentation-aiopg==0.44b0
opentelemetry-instrumentation-asgi==0.44b0
opentelemetry-instrumentation-asyncio==0.44b0
opentelemetry-instrumentation-asyncpg==0.44b0
opentelemetry-instrumentation-boto==0.44b0
opentelemetry-instrumentation-boto3sqs==0.44b0
opentelemetry-instrumentation-botocore==0.44b0
opentelemetry-instrumentation-cassandra==0.44b0
opentelemetry-instrumentation-celery==0.44b0
opentelemetry-instrumentation-confluent-kafka==0.44b0
opentelemetry-instrumentation-dbapi==0.44b0
opentelemetry-instrumentation-django==0.44b0
opentelemetry-instrumentation-elasticsearch==0.44b0
opentelemetry-instrumentation-falcon==0.44b0
opentelemetry-instrumentation-fastapi==0.44b0
opentelemetry-instrumentation-flask==0.44b0
opentelemetry-instrumentation-grpc==0.44b0
opentelemetry-instrumentation-httpx==0.44b0
opentelemetry-instrumentation-jinja2==0.44b0
opentelemetry-instrumentation-kafka-python==0.44b0
opentelemetry-instrumentation-logging==0.44b0
opentelemetry-instrumentation-mysql==0.44b0
opentelemetry-instrumentation-mysqlclient==0.44b0
opentelemetry-instrumentation-pika==0.44b0
opentelemetry-instrumentation-psycopg2==0.44b0
opentelemetry-instrumentation-pymemcache==0.44b0
opentelemetry-instrumentation-pymongo==0.44b0
opentelemetry-instrumentation-pymysql==0.44b0
opentelemetry-instrumentation-pyramid==0.44b0
opentelemetry-instrumentation-redis==0.44b0
opentelemetry-instrumentation-remoulade==0.44b0
opentelemetry-instrumentation-requests==0.44b0
opentelemetry-instrumentation-sklearn==0.44b0
opentelemetry-instrumentation-sqlalchemy==0.44b0
opentelemetry-instrumentation-sqlite3==0.44b0
opentelemetry-instrumentation-starlette==0.44b0
opentelemetry-instrumentation-system-metrics==0.44b0
opentelemetry-instrumentation-tornado==0.44b0
opentelemetry-instrumentation-tortoiseorm==0.44b0
opentelemetry-instrumentation-urllib==0.44b0
opentelemetry-instrumentation-urllib3==0.44b0
opentelemetry-instrumentation-wsgi==0.44b0
opentelemetry-propagator-aws-xray==1.0.1
opentelemetry-propagator-b3==1.23.0
opentelemetry-propagator-jaeger==1.23.0
opentelemetry-propagator-ot-trace==0.44b0
opentelemetry-proto==1.23.0
opentelemetry-sdk==1.23.0
opentelemetry-semantic-conventions==0.44b0
opentelemetry-test-utils==0.44b0
opentelemetry-util-http==0.44b0

```

_Application_
Python 3.10.13
grpc-stubs==1.53.0.5
grpcio==1.62.2
grpcio-status==1.62.2

I followed steps defined on the [OpenTelemetry doc for python autoinstrumentation via OpenTelemetry Operator Instrumentation Object](https://opentelemetry.io/docs/kubernetes/operator/automatic/#python-excluding-auto-instrumentation)
![image](https://github.com/open-telemetry/opentelemetry-python-contrib/assets/11273988/cc3af8ec-1d42-4372-b563-39d0983c4706)

In this snippet I specify to disable opentelemetry-autoinstrumentation-grcp package. I also tried with other packages as django and celery and even when the environment variable is set in the python deployment, all packages appear as installed with `pip list`.

```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation
  namespace: default
spec:
  exporter:
    endpoint: http://agent-collector-collector.otel-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"


  python:
    env:
    # Python autoinstrumentation only supports OTLP/HTTP which the collector runs on port 4318,
    # see https://github.com/open-telemetry/opentelemetry-operator/issues/924
    - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
      value: grpc
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://agent-collector-collector.otel-collector:4318
    - name: OTEL_LOGS_EXPORTER
      value: otlp_proto_http
    - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
      value: 'true'
    - name: OTEL_METRICS_EXPORTER
      value: none
```

I also tried to only disable the specific service 
```
    - name: OTEL_PYTHON_GRPC_EXCLUDED_SERVICES
      value: 'my-deployment-instrumented-python-service'
```
      
  but nothing changed, my application is still instrumented for grcp (just in case the issue may be related)
  I have been looking everywhere for days to detect if I am setting something wrong but I am blocked.
  
  
  
**Steps to reproduce**
1. Install OpenTelemetry Kubernetes Operator in the cluster
2. Deploy the OpenTelemetry Instrumentation Kubernetes Manifest shared above (replace the collector endpoint)
3. Deploy a python application deployment into Kubernetes with autoinstrumentation enabled `instrumentation.opentelemetry.io/inject-python: "true"` (the entry command can be a `sleep infinity` to avoid developing any python code, only python environment is required)

**What is the expected behavior?**
When I check `pip list` opentelemetry-instrumentation-grcp package shouldn't be there (or any other package specified on `OTEL_PYTHON_DISABLED_INSTRUMENTATIONS`)

**What is the actual behavior?**
opentelemetry-instrumentation-grcp package is still there.

**Additional context**
My application fails when grpc instrumentation is enabled. If I run my `python` application manually inside the Kubernetes pod after `pip uninstall opentelemetry-instrumentation-grcp` everything work as expected.

I need to disable this from the Instrumentation Service, but neither `OTEL_PYTHON_GRPC_EXCLUDED_SERVICES` nor `OTEL_PYTHON_DISABLED_INSTRUMENTATIONS` seem to work properly with the shared configuration.
