### ISSUE TITLE
Validate README.rst files at PR time

### ISSUE THREAD

**Issue by xrmx** [open-telemetry/opentelemetry-python-contrib#3364]
README.rst files are used for package description and are validated when uploading to pypi. If the README.rst is invalid the upload would fail as will do the release workflow. Since we can catch invalid READMEs earlier it would be nice to do that and avoid a cause of stress at release time.

**Comment by emdneto** [comment]
@xrmx rstcheck has pre-commit action, so we can use it I guess

**Comment by emdneto** [comment]
```
  - repo: https://github.com/rstcheck/rstcheck
    rev: f30c4d170a36ea3812bceb5f33004afc213bd797 # frozen: v6.2.4
    hooks:
      - id: rstcheck
        additional_dependencies: [sphinx]
        exclude: testing
```
